#seata:
#  enabled: true
#  application-id: ${spring.application.name}
#  tx-service-group: my_test_tx_group
#  client:
#    rm:
#      async-commit-buffer-limit: 1000
#      report-retry-count: 5
#      table-meta-check-enable: false
#      report-success-enable: false
#      lock:
#        retry-interval: 10
#        retry-times: 30
#        retry-policy-branch-rollback-on-conflict: true
#    tm:
#      commit-retry-count: 5
#      rollback-retry-count: 5
#    undo:
#      data-validation: true
#      log-serialization: jackson
#      log-table: undo_log
#    log:
#      exceptionRate: 100
#  service:
#    vgroup-mapping:
#      my_test_tx_group: default
#    grouplist:
#      default: 127.0.0.1:8091
#    #enable-degrade: false
#    #disable-global-transaction: false
#  transport:
#    shutdown:
#      wait: 3
#    thread-factory:
#      boss-thread-prefix: NettyBoss
#      worker-thread-prefix: NettyServerNIOWorker
#      server-executor-thread-prefix: NettyServerBizHandler
#      share-boss-worker: false
#      client-selector-thread-prefix: NettyClientSelector
#      client-selector-thread-size: 1
#      client-worker-thread-prefix: NettyClientWorkerThread
#      worker-thread-size: default
#      boss-thread-size: 1
#    type: TCP
#    server: NIO
#    heartbeat: true
#    serialization: seata
#    compressor: none
#    enable-client-batch-send-request: true
#  registry:
#    nacos:
#      server-addr: localhost
#      namespace: 05ef78d6-6326-4ce9-9f87-5c4f42d06a6d
#      group: SEATA_GROUP
#  config:
#    nacos:
#      server-addr: localhost
#      namespace: 05ef78d6-6326-4ce9-9f87-5c4f42d06a6d
#      group: SEATA_GROUP
